# Generated by Django 4.0.4 on 2022-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(to='teams.criteria'),
        ),
    ]
