# Generated by Django 4.0.4 on 2022-04-27 21:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_project_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='teams.criteria')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='teams.team')),
            ],
        ),
    ]
