# Generated by Django 4.0.4 on 2022-04-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_criteriascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriascore',
            name='judge',
            field=models.CharField(default='John', max_length=12),
        ),
    ]
