# Generated by Django 4.0.4 on 2022-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_criteriascore_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriascore',
            name='judge',
            field=models.CharField(max_length=12),
        ),
    ]
