# Generated by Django 4.0.4 on 2022-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_criteriascore_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriascore',
            name='note',
            field=models.TextField(default='good job'),
            preserve_default=False,
        ),
    ]
